layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# TODO: add web urls and images for the topics
topics:
  - name: Systems Programming

  - name: Backend Web Development

  - name: Programming Languages Research
